server {
    listen 80;
    location / {
        proxy_pass http://185.28.100.147/eset/;
        proxy_buffering off;
        proxy_cache off;
        proxy_hide_header Server;
        proxy_hide_header X-Powered-By;
    }
}
